language: php
matrix:
    include:
        - php: 5.4
        - php: 5.5
        - php: 5.6
sudo: false
dist: trusty
install:
- composer install
script: phpunit --configuration phpunit.xml --coverage-text